[package]
name = "modpack_updater"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
serde_json = "1.0.128"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.reqwest]
version = "0.12.7"
features = ["blocking"]
